variables:
  DART_SASS_VERSION: 1.87.0
  HUGO_VERSION: 0.147.1
  NODE_VERSION: 22.x
  TZ: Europe/Moscow

image: debian:bookworm-slim

stages:
  - build
  - deploy

before_script:
  # Установка зависимостей ОС
  - apt-get update
  - apt-get install -y curl wget gnupg ca-certificates brotli nodejs npm lftp s3cmd

  # Установка Dart Sass
  - curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
  - tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
  - cp -r dart-sass/ /usr/local/bin
  - rm -rf dart-sass*

  # Установка Hugo
  - curl -LJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
  - apt-get install -y ./hugo_extended_${HUGO_VERSION}_linux-amd64.deb
  - rm hugo_extended_${HUGO_VERSION}_linux-amd64.deb

  # Установка Node.js зависимостей
  - npm ci

build:
  stage: build
  script:
    - hugo --gc --minify
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache lftp
  script:
    - lftp -c "set ssl:verify-certificate no;
              set ftp:list-options -a;
              open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST;
              mirror -Rnev --parallel=8 --exclude .user.ini --exclude .well-known --exclude 502.html ./public/ $FTP_PATH
              bye"
  only:
    - master
    
# deploy:
#   stage: deploy
#   script:
#     # Создание конфигурационного файла для s3cmd
#     - |
#       cat > ~/.s3cfg <<EOF
#       [default]
#       access_key = $YANDEX_ACCESS_KEY
#       secret_key = $YANDEX_SECRET_KEY
#       host_base = storage.yandexcloud.net
#       host_bucket = %(bucket)s.storage.yandexcloud.net
#       bucket_location = ru-central1
#       use_https = True
#       signature_v2 = False
#       EOF
#     # Загрузка сайта
#     - s3cmd sync --delete-removed --acl-public ./public/ s3://$YANDEX_BUCKET/
#   only:
#     - master